[package]
name = "config-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22"
env_logger = "0.10"
gitlab = "0.1603.0"
log = "0.4"
serde = "1"
egui_graphs = "0.7"
petgraph = "0.6"